CREATE TABLE IF NOT EXISTS `msg_out` (
  `id`      INT(11)      AUTO_INCREMENT,
  `msg_id`  VARCHAR(300) DEFAULT NULL,
  `body`    VARCHAR(300) DEFAULT NULL,
  `queue_name` VARCHAR(300) DEFAULT NULL,
  `created` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `msg_inc` (
  `id`      INT(11)      AUTO_INCREMENT,
  `msg_id`  VARCHAR(300) DEFAULT NULL,
  `body`    VARCHAR(300) DEFAULT NULL,
  `queue_name` VARCHAR(300) DEFAULT NULL,
  `created` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
);